<?php
/**
 * The design's own words, as registered defaults.
 *
 * GENERATED from the ported templates — every entry is the string the handoff
 * screen carries, lifted verbatim out of `front-page.php`, `page-product.php`,
 * `page-pricing.php` and `page-contacts.php` when their copy was moved into
 * WordPress. Nothing here is invented and nothing here is layout: it is the run
 * of text an editor is allowed to change, keyed by where it sits on the page.
 *
 * The grouping is the design's own — each `$sections` key is one
 * `data-screen-label` from the export — so the meta box on a page reads in the
 * same order as the page itself.
 *
 * `intera_copy()` (inc/copy.php) reads a page's saved value and falls back to
 * the default here, so a field an editor never touched still renders the
 * handoff exactly. Editing a string in this file changes the fallback, not a
 * page that has already been saved.
 *
 * @package Intera
 */

defined( 'ABSPATH' ) || exit;

/**
 * Every editable run of text on the four designed pages.
 *
 * @return array<string,array{label:string,template:string,sections:array<string,array{label:string,fields:array<string,string>}>}>
 */
function intera_copy_schema() {
	return array(
		'home' => array(
			'label'    => __( 'Home page', 'intera' ),
			'template' => 'front-page.php',
			'sections' => array(
				'hero' => array(
					'label'  => __( 'Hero', 'intera' ),
					'fields' => array(
						'home_hero__your_business_clearly' => __( 'Your business, clearly', 'intera' ),
						'home_hero__see_what_needs_attention_before_someone' => __( 'See what needs attention. Before someone has to ask.', 'intera' ),
						'home_hero__intera_connects_the_systems_your_teams' => __( 'INTERA connects the systems your teams already use and gives each role a clear view of what matters — changes, risks, inconsistencies and trends.', 'intera' ),
						'home_hero__get_early_access' => __( 'Get Early Access', 'intera' ),
						'home_hero__see_how_intera_works' => __( 'See how INTERA works', 'intera' ),
						'home_hero__no_migration' => __( 'No migration', 'intera' ),
						'home_hero__read_only_access' => __( 'Read-only access', 'intera' ),
						'home_hero__start_with_one_role' => __( 'Start with one role', 'intera' ),
						'home_hero__reads_from' => __( 'Reads from', 'intera' ),
						'home_hero__internal_tools' => __( 'Internal tools', 'intera' ),
						'home_hero__fleet_health_overview_shipmanagement' => __( 'Fleet Health Overview · Shipmanagement', 'intera' ),
						'home_hero__critical_maintenance_task_overdue' => __( 'Critical maintenance task overdue', 'intera' ),
						'home_hero__5_days' => __( '5 days', 'intera' ),
						'home_hero__before_impact' => __( 'before impact', 'intera' ),
						'home_hero__4th_occurrence_always_after_a_delayed' => __( '4th occurrence — always after a delayed spare', 'intera' ),
					),
				),
				'sales' => array(
					'label'  => __( 'Sales and account management', 'intera' ),
					'fields' => array(
						'home_sales__sales_and_account_management' => __( 'Sales and account management', 'intera' ),
						'home_sales__know_what_was_promised_and_whether' => __( 'Know what was promised — and whether it actually happened', 'intera' ),
						'home_sales__sales_and_account_managers_often_need' => __( 'Sales and account managers often need answers that sit across several systems.', 'intera' ),
						'home_sales__was_the_equipment_delivered' => __( 'Was the equipment delivered?', 'intera' ),
						'home_sales__was_the_service_activated' => __( 'Was the service activated?', 'intera' ),
						'home_sales__was_the_agreed_price_applied' => __( 'Was the agreed price applied?', 'intera' ),
						'home_sales__is_anything_still_outstanding_before_the' => __( 'Is anything still outstanding before the next customer conversation?', 'intera' ),
						'home_sales__the_agreement_may_be_in_crm' => __( 'The agreement may be in CRM, delivery status in ERP or logistics, activation in operations, and pricing in billing.', 'intera' ),
						'home_sales__intera_brings_those_signals_together_and' => __( 'INTERA brings those signals together and shows which customer commitments need attention, with the evidence behind each result.', 'intera' ),
						'home_sales__it_does_not_replace_your_crm' => __( 'It does not replace your CRM or operational systems. It helps you see whether what was promised is actually being delivered.', 'intera' ),
					),
				),
				'problem' => array(
					'label'  => __( 'Problem', 'intera' ),
					'fields' => array(
						'home_problem__the_problem' => __( 'The problem', 'intera' ),
						'home_problem__this_will_feel_familiar' => __( 'This will feel familiar', 'intera' ),
						'home_problem__your_business_runs_across_several_systems' => __( 'Your business runs across several systems. Finance sees one part. Operations sees another.', 'intera' ),
						'home_problem__crm_billing_erp_spreadsheets_and_internal' => __( 'CRM, billing, ERP, spreadsheets and internal tools each contain pieces of the picture. Problems often become visible only when someone connects those pieces manually.', 'intera' ),
						'home_problem__teams_spend_time_checking_reconciling_explaining' => __( 'Teams spend time checking, reconciling, explaining and preparing information that already exists somewhere in the business.', 'intera' ),
						'home_problem__intera_makes_that_operating_picture_continuously' => __( 'INTERA makes that operating picture continuously visible.', 'intera' ),
						'home_problem__erp' => __( 'ERP', 'intera' ),
						'home_problem__erp_orders' => 'erp.orders',
						'home_problem__crm' => __( 'CRM', 'intera' ),
						'home_problem__crm_accounts' => 'crm.accounts',
						'home_problem__billing' => __( 'Billing', 'intera' ),
						'home_problem__billing_invoices' => 'billing.invoices',
						'home_problem__spreadsheets' => __( 'Spreadsheets', 'intera' ),
						'home_problem__ops_checks_xlsx' => 'ops_checks.xlsx',
						'home_problem__internal_tools' => __( 'Internal tools', 'intera' ),
						'home_problem__provisioning_api' => 'provisioning.api',
						'home_problem__pieces_of_the_same_picture_checked' => __( 'Pieces of the same picture, checked by hand.', 'intera' ),
					),
				),
				'how_it_works' => array(
					'label'  => __( 'How it works', 'intera' ),
					'fields' => array(
						'home_how_it_works__how_it_works' => __( 'How it works', 'intera' ),
						'home_how_it_works__get_full_visibility_without_changing_how' => __( 'Get full visibility without changing how your company operates', 'intera' ),
						'home_how_it_works__connect_your_existing_systems' => __( 'Connect your existing systems', 'intera' ),
						'home_how_it_works__intera_connects_to_finance_operations_crm' => __( 'INTERA connects to finance, operations, CRM, billing, ERP, Excel and internal systems without replacing them.', 'intera' ),
						'home_how_it_works__intera_understands_what_matters' => __( 'INTERA understands what matters', 'intera' ),
						'home_how_it_works__it_applies_your_business_logic_and' => __( 'It applies business logic and watches changes, risks and inconsistencies.', 'intera' ),
						'home_how_it_works__see_what_needs_attention' => __( 'See what needs attention', 'intera' ),
						'home_how_it_works__managers_immediately_see_what_changed_what' => __( 'Managers immediately see what changed, what requires action and where to investigate.', 'intera' ),
						'home_how_it_works__intera_doesn_t_replace_your_team' => __( 'INTERA doesn\'t replace your team — it removes unnecessary manual checking and reporting between systems and people.', 'intera' ),
					),
				),
				'champion' => array(
					'label'  => __( 'Champion', 'intera' ),
					'fields' => array(
						'home_champion__for_the_manager_who_owns_the' => __( 'For the manager who owns the area', 'intera' ),
						'home_champion__make_your_area_easier_to_run' => __( 'Make your area easier to run', 'intera' ),
						'home_champion__intera_doesn_t_just_give_management' => __( 'INTERA doesn\'t just give management more visibility. It helps you stay on top of the part of the business you\'re responsible for.', 'intera' ),
						'home_champion__know_before_you_re_asked' => __( 'Know before you\'re asked', 'intera' ),
						'home_champion__see_problems_and_unusual_changes_before' => __( 'See problems and unusual changes before they become questions or escalations.', 'intera' ),
						'home_champion__spend_less_time_proving_what_s' => __( 'Spend less time proving what\'s happening', 'intera' ),
						'home_champion__reduce_repetitive_reporting_manual_checks_and' => __( 'Reduce repetitive reporting, manual checks and status updates.', 'intera' ),
						'home_champion__bring_problems_with_answers' => __( 'Bring problems with answers', 'intera' ),
						'home_champion__see_the_supporting_data_and_understand' => __( 'See the supporting data and understand what requires action.', 'intera' ),
						'home_champion__show_that_your_area_is_under' => __( 'Show that your area is under control', 'intera' ),
						'home_champion__give_management_clear_and_consistent_visibility' => __( 'Give management clear and consistent visibility without preparing another spreadsheet.', 'intera' ),
						'home_champion__make_improvements_that_last' => __( 'Make improvements that last', 'intera' ),
						'home_champion__turn_the_checks_knowledge_and_working' => __( 'Turn the checks, knowledge and working practices your team already uses into something repeatable and visible across the organization.', 'intera' ),
						'home_champion__less_chasing' => __( 'Less chasing.', 'intera' ),
						'home_champion__fewer_surprises' => __( 'Fewer surprises.', 'intera' ),
						'home_champion__more_confidence_in_the_part_of' => __( 'More confidence in the part of the business you own.', 'intera' ),
					),
				),
				'in_action' => array(
					'label'  => __( 'In action', 'intera' ),
					'fields' => array(
						'home_in_action__intera_in_action' => __( 'INTERA in action', 'intera' ),
						'home_in_action__don_t_just_watch_the_business' => __( 'Don\'t just watch the business. Catch what matters.', 'intera' ),
						'home_in_action__something_important_changed' => __( 'Something important changed.', 'intera' ),
						'home_in_action__things_that_should_agree_don_t' => __( 'Things that should agree — don\'t.', 'intera' ),
						'home_in_action__something_requires_attention_and_action' => __( 'Something requires attention and action.', 'intera' ),
						'home_in_action__understand_what_keeps_happening_and_under' => __( 'Understand what keeps happening, and under which conditions.', 'intera' ),
						'home_in_action__from_something_looks_wrong_to_we' => __( 'From "something looks wrong" to "we know what is happening, why it matters, and what to watch next."', 'intera' ),
						'home_in_action__intera_does_not_try_to_reproduce' => __( 'INTERA does not try to reproduce the detail already available in specialist systems. It identifies where attention is needed and lets the underlying system remain the place for detailed investigation and action.', 'intera' ),
						'home_in_action__attention_queue_what_to_work_on' => __( 'Attention Queue · what to work on first', 'intera' ),
						'home_in_action__intera_turns_data_into_attention' => __( 'INTERA turns data into attention', 'intera' ),
						'home_in_action__metrics' => __( 'Metrics', 'intera' ),
						'home_in_action__tell_you_what_changed' => __( 'Tell you what changed.', 'intera' ),
						'home_in_action__health' => __( 'Health', 'intera' ),
						'home_in_action__tells_you_what_is_weakening' => __( 'Tells you what is weakening.', 'intera' ),
						'home_in_action__reconciliations' => __( 'Reconciliations', 'intera' ),
						'home_in_action__tell_you_what_does_not_agree' => __( 'Tell you what does not agree.', 'intera' ),
						'home_in_action__evidence' => __( 'Evidence', 'intera' ),
						'home_in_action__tells_you_where_to_investigate' => __( 'Tells you where to investigate.', 'intera' ),
						'home_in_action__intera_brings_these_signals_together_around' => __( 'INTERA brings these signals together around the person responsible.', 'intera' ),
						'home_in_action__events_incidents_patterns' => __( 'Events · Incidents · Patterns', 'intera' ),
						'home_in_action__intera_is_being_extended_beyond_today' => __( 'INTERA is being extended beyond today\'s visibility and reconciliation capabilities.', 'intera' ),
					),
				),
				'roles' => array(
					'label'  => __( 'Roles', 'intera' ),
					'fields' => array(
						'home_roles__intera_roles' => __( 'INTERA Roles', 'intera' ),
						'home_roles__pre_built_visibility_for_the_parts' => __( 'Pre-built visibility for the parts of your business that matter most', 'intera' ),
						'home_roles__roles_are_ready_made_business_modules' => __( 'INTERA Roles are ready-made business modules designed around real responsibilities — finance, operations, revenue, and more. Each role comes with predefined metrics, logic, and automatic issue detection, so you can see what\'s happening without building anything from scratch.', 'intera' ),
						'home_roles__different_responsibilities_one_operating_picture' => __( 'Different responsibilities. One operating picture.', 'intera' ),
						'home_roles__see_all_roles' => __( 'See all Roles', 'intera' ),
					),
				),
				'working_with_it' => array(
					'label'  => __( 'Working with IT', 'intera' ),
					'fields' => array(
						'home_working_with_it__working_with_existing_it' => __( 'Working with existing IT', 'intera' ),
						'home_working_with_it__your_systems_remain_in_control' => __( 'Your systems remain in control', 'intera' ),
						'home_working_with_it__intera_does_not_replace_your_erp' => __( 'INTERA does not replace your ERP, CRM or operational systems.', 'intera' ),
						'home_working_with_it__connections_can_be_configured_read_only' => __( 'Connections can be configured read-only.', 'intera' ),
						'home_working_with_it__intera_does_not_need_permission_to' => __( 'INTERA does not need permission to modify operational data.', 'intera' ),
						'home_working_with_it__local_installation_is_available_from' => __( 'Local installation is available from the Early Adopter plan onwards.', 'intera' ),
						'home_working_with_it__access_follows_intera_roles_and_permissions' => __( 'Access follows INTERA roles and permissions.', 'intera' ),
						'home_working_with_it__business_teams_know_what_they_need' => __( 'Business teams know what they need to control. IT knows how the systems work. INTERA gives them a practical place to meet.', 'intera' ),
						'home_working_with_it__dependencies_suppliers_parts_external_commitments' => __( 'Dependencies · suppliers, parts, external commitments', 'intera' ),
					),
				),
				'data_control' => array(
					'label'  => __( 'Your data', 'intera' ),
					'fields' => array(
						'home_data_control__your_data' => __( 'Your data', 'intera' ),
						'home_data_control__your_data_stays_under_your_control' => __( 'Your data stays under your control', 'intera' ),
						'home_data_control__intera_is_designed_to_work_with' => __( 'INTERA is designed to work with sensitive operational and financial information without becoming another uncontrolled copy of your business data.', 'intera' ),
						'home_data_control__read_only_by_design' => __( 'Read-only by design', 'intera' ),
						'home_data_control__intera_can_connect_to_existing_erp' => __( 'INTERA can connect to existing ERP, CRM, billing, monitoring and operational systems using read-only access. It does not need permission to change records or write data back into the systems you already trust.', 'intera' ),
						'home_data_control__your_data_stays_where_intera_runs' => __( 'Your data stays where INTERA runs', 'intera' ),
						'home_data_control__for_customer_deployments_intera_can_run' => __( 'For customer deployments, INTERA can run inside your own infrastructure, with operational data stored on that installation. Your internal business data does not need to be uploaded to a shared INTERA cloud service.', 'intera' ),
						'home_data_control__no_routine_access_for_the_intera' => __( 'No routine access for the INTERA team', 'intera' ),
						'home_data_control__intera_support_does_not_require_permanent' => __( 'INTERA support does not require permanent access to your internal systems, databases or APIs. Any access required during setup or troubleshooting is agreed with the customer and can be limited to what is necessary for that specific task.', 'intera' ),
						'home_data_control__your_systems_remain_yours_your_credentials' => __( 'Your systems remain yours. Your credentials remain under your control. INTERA only needs the access required to understand the signals you choose to connect.', 'intera' ),
					),
				),
				'sysadmin_package' => array(
					'label'  => __( 'Sysadmin Package', 'intera' ),
					'fields' => array(
						'home_sysadmin_package__included_free_with_every_plan' => __( 'Included free with every plan', 'intera' ),
						'home_sysadmin_package__sysadmin_package' => __( 'Sysadmin Package', 'intera' ),
						'home_sysadmin_package__the_free_sysadmin_package_gives_it' => __( 'The free Sysadmin Package gives IT teams a ready-made starting point for operational visibility across existing systems. It brings together a small set of health signals, metrics and reconciliations so you can quickly see what needs attention without replacing your monitoring tools. Use it alongside your current infrastructure, backup, service and ticketing systems to spot problems faster and understand where to investigate. Start free, connect what you already use, and expand only if it proves useful.', 'intera' ),
						'home_sysadmin_package__what_the_package_includes' => __( 'What the package includes', 'intera' ),
					),
				),
				'start_small' => array(
					'label'  => __( 'Start small', 'intera' ),
					'fields' => array(
						'home_start_small__start_small' => __( 'Start small', 'intera' ),
						'home_start_small__start_with_one_real_problem' => __( 'Start with one real problem', 'intera' ),
						'home_start_small__do_not_start_by_implementing_intera' => __( 'Do not start by implementing INTERA in your whole company. One role. One operational problem. One working result.', 'intera' ),
						'home_start_small__bring_us_a_real_problem' => __( 'Bring us a real problem', 'intera' ),
						'home_start_small__billing_and_usage_do_not_correspond' => __( 'Billing and usage do not correspond.', 'intera' ),
						'home_start_small__the_problem_is_detected_too_late' => __( 'The problem is detected too late.', 'intera' ),
						'home_start_small__the_same_exceptions_are_constantly_checked' => __( 'The same exceptions are constantly checked by hand.', 'intera' ),
						'home_start_small__a_manager_gathers_the_same_data' => __( 'A manager gathers data from several different systems.', 'intera' ),
					),
				),
				'pricing' => array(
					'label'  => __( 'Pricing', 'intera' ),
					'fields' => array(
						'home_pricing__pricing' => __( 'Pricing', 'intera' ),
						'home_pricing__start_free_pay_when_intera_is' => __( 'Start free. Pay when INTERA is doing real work.', 'intera' ),
					),
				),
				'early_adopter' => array(
					'label'  => __( 'Early Adopter', 'intera' ),
					'fields' => array(
						'home_early_adopter__early_adopter_offer' => __( 'Early Adopter offer', 'intera' ),
						'home_early_adopter__help_shape_intera_around_a_real' => __( 'Help shape INTERA around a real operation', 'intera' ),
						'home_early_adopter__we_are_looking_for_a_small' => __( 'We are looking for a small number of companies and managers who are ready to use INTERA to solve their real operational tasks during the private beta stage.', 'intera' ),
						'home_early_adopter__early_adopters_receive' => __( 'Early Adopters receive', 'intera' ),
						'home_early_adopter__intera_free_for_the_first_12' => __( 'INTERA free for the first 12 months', 'intera' ),
						'home_early_adopter__custom_onboarding' => __( 'Custom onboarding', 'intera' ),
						'home_early_adopter__direct_contact_with_the_intera_team' => __( 'Direct contact with the INTERA team', 'intera' ),
						'home_early_adopter__priority_support' => __( 'Priority support', 'intera' ),
						'home_early_adopter__influence_over_product_development' => __( 'Influence over product development', 'intera' ),
						'home_early_adopter__help_setting_up_your_first_real' => __( 'Help setting up your first real use case', 'intera' ),
						'home_early_adopter__we_expect_in_return' => __( 'We expect in return', 'intera' ),
						'home_early_adopter__a_real_business_case' => __( 'A real business case', 'intera' ),
						'home_early_adopter__feedback' => __( 'Feedback', 'intera' ),
						'home_early_adopter__readiness_to_work_together_and_verify' => __( 'Readiness to work together and verify our solutions', 'intera' ),
						'home_early_adopter__i_have_a_problem_intera_could' => __( 'I have a problem INTERA could solve', 'intera' ),
					),
				),
				'partners' => array(
					'label'  => __( 'Partners', 'intera' ),
					'fields' => array(
						'home_partners__partners_and_resellers' => __( 'Partners and resellers', 'intera' ),
						'home_partners__turn_your_industry_knowledge_into_repeatable' => __( 'Turn your industry knowledge into repeatable solutions', 'intera' ),
						'home_partners__intera_is_designed_to_work_with' => __( 'INTERA is designed to work with experienced technology and business specialists who understand their customers, industries and operational environments.', 'intera' ),
						'home_partners__during_private_beta_partner_participation_is' => __( 'During Private Beta, partner participation is limited and by invitation only.', 'intera' ),
						'home_partners__for_partnership_enquiries_please_s' => __( 'For partnership enquiries, please %s.', 'intera' ),
						'home_partners__contact_us_directly' => __( 'contact us directly', 'intera' ),
						'home_partners__solve_once_adapt_deploy_again' => __( 'Solve once. Adapt. Deploy again.', 'intera' ),
						'home_partners__become_an_intera_partner' => __( 'Become an INTERA partner', 'intera' ),
					),
				),
			),
		),
		'product' => array(
			'label'    => __( 'Product page', 'intera' ),
			'template' => 'page-product.php',
			'sections' => array(
				'header' => array(
					'label'  => __( 'Header', 'intera' ),
					'fields' => array(
						'product_headline' => __( 'One operating picture across the systems you already run', 'intera' ),
					),
				),
				'page' => array(
					'label'  => __( 'Page', 'intera' ),
					'fields' => array(
						'product_page__get_early_access' => __( 'Get Early Access', 'intera' ),
						'product_page__something_important_changed' => __( 'Something important changed.', 'intera' ),
						'product_page__things_that_should_agree_don_t' => __( 'Things that should agree — don\'t.', 'intera' ),
						'product_page__something_requires_attention_and_action' => __( 'Something requires attention and action.', 'intera' ),
						'product_page__understand_what_keeps_happening_and_under' => __( 'Understand what keeps happening, and under which conditions.', 'intera' ),
					),
				),
				'product_header' => array(
					'label'  => __( 'Product header', 'intera' ),
					'fields' => array(
						'product_product_header__read_the_docs' => __( 'Read the docs', 'intera' ),
						'product_product_header__operations_oversight' => __( 'Operations Oversight', 'intera' ),
						'product_product_header__live' => __( 'live', 'intera' ),
						'product_product_header__open_incidents' => __( 'Open incidents', 'intera' ),
						'product_product_header__7' => array(
							'default' => '7',
							'label'   => __( 'Open incidents — figure', 'intera' ),
						),
						'product_product_header__2' => array(
							'default' => '+2',
							'label'   => __( 'Open incidents — change', 'intera' ),
						),
						'product_product_header__unreconciled' => __( 'Unreconciled', 'intera' ),
						'product_product_header__4812' => array(
							'default' => '4,812',
							'label'   => __( 'Unreconciled — figure', 'intera' ),
						),
						'product_product_header__311' => array(
							'default' => '-311',
							'label'   => __( 'Unreconciled — change', 'intera' ),
						),
						'product_product_header__latest' => __( 'Latest', 'intera' ),
						'product_product_header__billing_vs_erp_118_invoices_differ' => __( 'Billing vs ERP: 118 invoices differ by more than 0.5%', 'intera' ),
						'product_product_header__no_data_received_from_wms_since' => __( 'No data received from WMS since 03:20 UTC', 'intera' ),
						'product_product_header__readiness_drops_every_monday_after_the' => __( 'Readiness drops every Monday after the weekend import', 'intera' ),
					),
				),
				'what_intera_watches' => array(
					'label'  => __( 'What INTERA watches', 'intera' ),
					'fields' => array(
						'product_what_intera_watches__the_chain' => __( 'The chain', 'intera' ),
						'product_what_intera_watches__event_reconciliation_incident_pattern' => __( 'Event, Reconciliation, Incident, Pattern', 'intera' ),
						'product_what_intera_watches__four_object_types_in_a_fixed' => __( 'Four object types, in a fixed order. Everything a role sees is one of them.', 'intera' ),
						'product_what_intera_watches__a_watched_metric_moved' => __( 'A watched Metric moved', 'intera' ),
						'product_what_intera_watches__thresholds_trends_and_data_status_on' => __( 'Thresholds, trends and data status on the numbers a role owns. The event carries the value, the source and the time.', 'intera' ),
						'product_what_intera_watches__metrics_trend_metrics_threshold' => __( 'metrics.trend · metrics.threshold', 'intera' ),
						'product_what_intera_watches__two_systems_disagree' => __( 'Two systems disagree', 'intera' ),
						'product_what_intera_watches__continuous_comparison_between_systems_periods_an' => __( 'Continuous comparison between systems, periods and business conditions — with the differing records listed, not summarised away.', 'intera' ),
						'product_what_intera_watches__usage_billing_orders_invoices' => __( 'usage ↔ billing · orders ↔ invoices', 'intera' ),
						'product_what_intera_watches__someone_has_to_act' => __( 'Someone has to act', 'intera' ),
						'product_what_intera_watches__a_tracked_item_with_an_owner' => __( 'A tracked item with an owner, a priority, an expected time to impact and the evidence behind it.', 'intera' ),
						'product_what_intera_watches__p0_impact_in_2_days_owner' => __( 'P0 · impact in 2 days · owner set', 'intera' ),
						'product_what_intera_watches__it_keeps_happening' => __( 'It keeps happening', 'intera' ),
						'product_what_intera_watches__recurring_combinations_of_conditions_behind_inci' => __( 'Recurring combinations of conditions behind incidents and changes — and the option to keep watching them.', 'intera' ),
						'product_what_intera_watches__4th_occurrence_same_precondition' => __( '4th occurrence · same precondition', 'intera' ),
					),
				),
				'pattern_studio' => array(
					'label'  => __( 'Pattern Studio', 'intera' ),
					'fields' => array(
						'product_pattern_studio__pattern_studio' => __( 'Pattern Studio', 'intera' ),
						'product_pattern_studio__understand_what_keeps_happening_and_under' => __( 'Understand what keeps happening, and under which conditions', 'intera' ),
						'product_pattern_studio__look_back_at_what_preceded_an' => __( 'Look back at what preceded an incident, find the combination that repeats, then turn it into something INTERA keeps watching. What one manager learns becomes a check the whole company keeps.', 'intera' ),
						'product_pattern_studio__if' => __( 'if', 'intera' ),
						'product_pattern_studio__a_spare_part_delivery_slips_more' => __( 'a spare part delivery slips more than 5 days', 'intera' ),
						'product_pattern_studio__and' => __( 'and', 'intera' ),
						'product_pattern_studio__the_vessel_already_carries_overdue_critical' => __( 'the vessel already carries overdue critical maintenance', 'intera' ),
						'product_pattern_studio__then' => __( 'then', 'intera' ),
						'product_pattern_studio__readiness_drops_below_plan_within_3' => __( 'readiness drops below plan within 3 weeks — 4 of the last 5 times', 'intera' ),
						'product_pattern_studio__how_patterns_are_defined' => __( 'How Patterns are defined', 'intera' ),
						'product_pattern_studio__role_view_readiness_and_upcoming_dates' => __( 'Role view · readiness and upcoming dates', 'intera' ),
						'product_pattern_studio__intera_role_view_with_readiness_metrics' => __( 'INTERA role view with readiness metrics and upcoming dates', 'intera' ),
					),
				),
				'integrations' => array(
					'label'  => __( 'Integrations', 'intera' ),
					'fields' => array(
						'product_integrations__integrations_and_datasources' => __( 'Integrations and DataSources', 'intera' ),
						'product_integrations__read_only_connections_to_the_systems' => __( 'Read-only connections to the systems of record', 'intera' ),
						'product_integrations__a_datasource_states_which_system_holds' => __( 'A DataSource states which system holds the data, what is mapped and how often it is read. Nothing is written back.', 'intera' ),
						'product_integrations__erp' => __( 'ERP', 'intera' ),
						'product_integrations__sap_oracle_bc' => __( 'SAP · Oracle · BC', 'intera' ),
						'product_integrations__crm' => __( 'CRM', 'intera' ),
						'product_integrations__accounts' => __( 'accounts', 'intera' ),
						'product_integrations__billing' => __( 'Billing', 'intera' ),
						'product_integrations__invoices_rating' => __( 'invoices · rating', 'intera' ),
						'product_integrations__mediation' => __( 'Mediation', 'intera' ),
						'product_integrations__usage_cdr' => __( 'usage · CDR', 'intera' ),
						'product_integrations__excel' => __( 'Excel', 'intera' ),
						'product_integrations__exports_checks' => __( 'exports · checks', 'intera' ),
						'product_integrations__internal_apis' => __( 'Internal APIs', 'intera' ),
						'product_integrations__custom' => __( 'custom', 'intera' ),
						'product_integrations__banking' => __( 'Banking', 'intera' ),
						'product_integrations__revolut' => __( 'Revolut', 'intera' ),
						'product_integrations__manual_inputs' => __( 'Manual inputs', 'intera' ),
						'product_integrations__forms_mail' => __( 'forms · mail', 'intera' ),
						'product_integrations__it_owns_access' => __( 'IT owns access', 'intera' ),
						'product_integrations__which_system_which_credentials_which_refresh' => __( 'Which system, which credentials, which refresh window.', 'intera' ),
						'product_integrations__intera_states_the_requirement_concretely_the' => __( 'INTERA states the requirement concretely: the system, the DataSource, the fields to map. No open-ended data project.', 'intera' ),
						'product_integrations__business_owns_logic' => __( 'Business owns logic', 'intera' ),
						'product_integrations__metrics_events_incidents_reconciliations_pattern' => __( 'Metrics, Events, Incidents, Reconciliations, Patterns.', 'intera' ),
						'product_integrations__the_people_who_know_how_the' => __( 'The people who know how the operation runs decide what counts as a problem — and can change it without a release.', 'intera' ),
					),
				),
				'roles' => array(
					'label'  => __( 'Roles', 'intera' ),
					'fields' => array(
						'product_roles__intera_roles' => __( 'INTERA Roles', 'intera' ),
						'product_roles__a_module_built_around_a_responsibility' => __( 'A module built around a responsibility, not a data source', 'intera' ),
						'product_roles__each_role_arrives_with_its_metrics' => __( 'Each role arrives with its metrics, its checks and its detection logic. Adjust them; you are not locked in.', 'intera' ),
						'product_roles__different_responsibilities_one_operating_picture' => __( 'Different responsibilities. One operating picture.', 'intera' ),
						'product_roles__roles_combine_several_sources_and_apply' => __( 'Roles combine several sources and apply business logic, so nobody connects the dots by hand.', 'intera' ),
					),
				),
				'role_packages' => array(
					'label'  => __( 'Role packages', 'intera' ),
					'fields' => array(
						'product_role_packages__role_packages' => __( 'Role packages', 'intera' ),
						'product_role_packages__ready_made_packages_shaped_around_real' => __( 'Ready-made packages, shaped around real responsibilities', 'intera' ),
						'product_role_packages__a_role_package_is_a_reusable' => __( 'A role package is a reusable set of roles, checks and integrations for one part of the business. The Sysadmin package is included free with every plan.', 'intera' ),
						'product_role_packages__system_administrator' => __( 'Sysadmin', 'intera' ),
						'product_role_packages__what_needs_attention_across_infrastructure_serv' => __( 'What needs attention across infrastructure, services and suppliers?', 'intera' ),
						'product_role_packages__infrastructure_health' => __( 'Infrastructure health', 'intera' ),
						'product_role_packages__backups_and_restores' => __( 'Backups and restores', 'intera' ),
						'product_role_packages__service_availability' => __( 'Service availability', 'intera' ),
						'product_role_packages__licences_and_certificates' => __( 'Licences and certificates', 'intera' ),
						'product_role_packages__supplier_and_vendor_slas' => __( 'Supplier and vendor SLAs', 'intera' ),
						'product_role_packages__ticket_backlog' => __( 'Ticket backlog', 'intera' ),
						'product_role_packages__finance_billing_control' => __( 'Finance / Billing Control', 'intera' ),
						'product_role_packages__do_billing_accounting_and_payments_agree' => __( 'Do billing, accounting and payments agree?', 'intera' ),
						'product_role_packages__invoicing_and_billing_runs' => __( 'Invoicing and billing runs', 'intera' ),
						'product_role_packages__payments_and_receivables' => __( 'Payments and receivables', 'intera' ),
						'product_role_packages__accounting_reconciliation' => __( 'Accounting reconciliation', 'intera' ),
						'product_role_packages__tariffs_and_price_lists' => __( 'Tariffs and price lists', 'intera' ),
						'product_role_packages__disputes_and_credit_notes' => __( 'Disputes and credit notes', 'intera' ),
						'product_role_packages__revenue_leakage' => __( 'Revenue leakage', 'intera' ),
						'product_role_packages__operations' => __( 'Operations', 'intera' ),
						'product_role_packages__which_assets_customers_or_projects_are' => __( 'Which assets, customers or projects are falling outside normal conditions?', 'intera' ),
						'product_role_packages__asset_and_equipment_status' => __( 'Asset and equipment status', 'intera' ),
						'product_role_packages__customer_and_project_health' => __( 'Customer and project health', 'intera' ),
						'product_role_packages__delivery_and_schedule_slippage' => __( 'Delivery and schedule slippage', 'intera' ),
						'product_role_packages__stock_and_consumables' => __( 'Stock and consumables', 'intera' ),
						'product_role_packages__maintenance_backlog' => __( 'Maintenance backlog', 'intera' ),
						'product_role_packages__exceptions_and_deviations' => __( 'Exceptions and deviations', 'intera' ),
						'product_role_packages__service_management' => __( 'Service Management', 'intera' ),
						'product_role_packages__which_customer_or_service_problems_are' => __( 'Which customer or service problems are becoming operationally significant?', 'intera' ),
						'product_role_packages__tickets_and_requests' => __( 'Tickets and requests', 'intera' ),
						'product_role_packages__sla_breaches' => __( 'SLA breaches', 'intera' ),
						'product_role_packages__recurring_incidents' => __( 'Recurring incidents', 'intera' ),
						'product_role_packages__escalations' => __( 'Escalations', 'intera' ),
						'product_role_packages__service_quality_signals' => __( 'Service quality signals', 'intera' ),
						'product_role_packages__customer_impact' => __( 'Customer impact', 'intera' ),
						'product_role_packages__included_free' => __( 'Included free', 'intera' ),
						'product_role_packages__beta' => __( 'Private Beta', 'intera' ),
					),
				),
				'method' => array(
					'label'  => __( 'Method', 'intera' ),
					'fields' => array(
						'product_method__intera_method' => __( 'INTERA Method', 'intera' ),
						'product_method__a_working_system_not_a_set' => __( 'A working system, not a set of recommendations', 'intera' ),
						'product_method__the_method_is_a_hands_on' => __( 'The Method is a hands-on engagement: we work on site with your team, map how the operation actually runs, and leave a configured environment behind. Traditional consulting ends with a document. This ends with dashboards that keep working.', 'intera' ),
						'product_method__map_the_real_data_flows_not' => __( 'Map the real data flows, not the documented ones', 'intera' ),
						'product_method__identify_blind_spots_and_the_checks' => __( 'Identify blind spots and the checks nobody owns', 'intera' ),
						'product_method__define_metrics_that_reflect_the_operation' => __( 'Define Metrics that reflect the operation', 'intera' ),
						'product_method__connect_the_data_sources_with_it' => __( 'Connect the data sources with IT', 'intera' ),
						'product_method__build_the_first_roles_and_dashboards' => __( 'Build the first Roles and dashboards together', 'intera' ),
						'product_method__what_you_leave_with' => __( 'What you leave with', 'intera' ),
						'product_method__a_working_intera_environment' => __( 'A working INTERA environment', 'intera' ),
						'product_method__connected_data_sources' => __( 'Connected data sources', 'intera' ),
						'product_method__defined_metrics_and_business_logic' => __( 'Defined Metrics and business logic', 'intera' ),
						'product_method__operational_dashboards_in_use' => __( 'Operational dashboards in use', 'intera' ),
						'product_method__visibility_into_issues_you_could_not' => __( 'Visibility into issues you could not see before', 'intera' ),
						'product_method__delivered_over_several_intensive_on_site' => __( 'Delivered over several intensive on-site days. Scope depends on how many systems and roles are involved.', 'intera' ),
						'product_method__talk_to_us_about_the_method' => __( 'Talk to us about the Method', 'intera' ),
					),
				),
				'cta' => array(
					'label'  => __( 'CTA', 'intera' ),
					'fields' => array(
						'product_cta__start_with_one_real_problem' => __( 'Start with one real problem.', 'intera' ),
						'product_cta__one_role_one_operational_problem_one' => __( 'One role. One operational problem. One working result.', 'intera' ),
						'product_cta__bring_us_a_real_problem' => __( 'Bring us a real problem', 'intera' ),
					),
				),
			),
		),
		'pricing' => array(
			'label'    => __( 'Pricing page', 'intera' ),
			'template' => 'page-pricing.php',
			'sections' => array(
				'header' => array(
					'label'  => __( 'Header', 'intera' ),
					'fields' => array(
						'pricing_headline' => __( 'Start free. Pay when INTERA is doing real work.', 'intera' ),
					),
				),
				'page' => array(
					'label'  => __( 'Page', 'intera' ),
					'fields' => array(
						'pricing_page__what_each_plan_includes' => __( 'What each plan includes', 'intera' ),
						'pricing_page__roles' => __( 'Roles', 'intera' ),
						'pricing_page__roles_2' => __( 'roles', 'intera' ),
						'pricing_page__users' => __( 'Users', 'intera' ),
						'pricing_page__users_2' => __( 'users', 'intera' ),
						'pricing_page__role_package' => __( 'Role package', 'intera' ),
						'pricing_page__role_package_2' => __( 'role package', 'intera' ),
						'pricing_page__is_the_free_plan_time_limited' => __( 'Is the free plan time-limited?', 'intera' ),
						'pricing_page__no_it_is_limited_by_roles' => __( 'No. It is limited by roles, users, integrations and 30 days of history — not by a trial clock.', 'intera' ),
						'pricing_page__what_happens_after_the_12_free' => __( 'What happens after the 12 free months?', 'intera' ),
						'pricing_page__you_move_to_a_commercial_plan' => __( 'You move to a commercial plan, or you stop. Nothing you configured is held hostage.', 'intera' ),
						'pricing_page__do_we_need_the_method_to' => __( 'Do we need the Method to start?', 'intera' ),
						'pricing_page__no_the_method_is_for_teams' => __( 'No. The Method is for teams that want the first roles built together, on site, in a few intensive days.', 'intera' ),
						'pricing_page__where_does_intera_run' => __( 'Where does INTERA run?', 'intera' ),
						'pricing_page__cloud_installation_on_the_free_plan' => __( 'Cloud installation on the free plan. Local installation is available from the Early Adopter plan onwards. Access to source systems stays read-only.', 'intera' ),
					),
				),
				'comparison' => array(
					'label'  => __( 'Comparison', 'intera' ),
					'fields' => array(
						'pricing_comparison__capability' => __( 'Capability', 'intera' ),
						'pricing_comparison__prices_exclude_vat_custom_integrations_and' => __( 'Prices exclude VAT. Custom integrations and additional role packages are quoted separately.', 'intera' ),
					),
				),
				'early_adopter' => array(
					'label'  => __( 'Early Adopter', 'intera' ),
					'fields' => array(
						'pricing_early_adopter__early_adopter_offer' => __( 'Early Adopter offer', 'intera' ),
						'pricing_early_adopter__help_shape_intera_around_a_real' => __( 'Help shape INTERA around a real operation', 'intera' ),
						'pricing_early_adopter__twelve_months_free_custom_onboarding_and' => __( 'Twelve months free, custom onboarding and direct contact with the team. We ask for one real business case and your feedback.', 'intera' ),
						'pricing_early_adopter__i_have_a_problem_intera_could' => __( 'I have a problem INTERA could solve', 'intera' ),
					),
				),
				'pricing_questions' => array(
					'label'  => __( 'Pricing questions', 'intera' ),
					'fields' => array(
						'pricing_pricing_questions__questions_that_come_up_before_signing' => __( 'Questions that come up before signing', 'intera' ),
						'pricing_pricing_questions__read_the_full_faq' => __( 'Read the full FAQ', 'intera' ),
					),
				),
			),
		),
		'contacts' => array(
			'label'    => __( 'Contacts page', 'intera' ),
			'template' => 'page-contacts.php',
			'sections' => array(
				'header' => array(
					'label'  => __( 'Header', 'intera' ),
					'fields' => array(
						'contacts_headline' => __( 'Talk to us about one real problem', 'intera' ),
					),
				),
				'page' => array(
					'label'  => __( 'Page', 'intera' ),
					'fields' => array(
						'contacts_page__the_check_nobody_enjoys_doing' => __( 'The check nobody enjoys doing', 'intera' ),
						'contacts_page__the_report_reconciliation_or_status_update' => __( 'The report, reconciliation or status update someone repeats every week.', 'intera' ),
						'contacts_page__the_systems_involved' => __( 'The systems involved', 'intera' ),
						'contacts_page__erp_crm_billing_spreadsheets_names_are' => __( 'ERP, CRM, billing, spreadsheets — names are enough, no diagrams needed.', 'intera' ),
						'contacts_page__what_goes_wrong_when_it_is' => __( 'What goes wrong when it is found too late', 'intera' ),
						'contacts_page__lost_revenue_a_missed_date_an' => __( 'Lost revenue, a missed date, an escalation, a surprised customer.', 'intera' ),
						'contacts_page__early_adopter' => __( 'Early Adopter', 'intera' ),
						'contacts_page__you_have_a_real_operational_task' => __( 'You have a real operational task and want it solved during the private beta. Twelve months free, custom onboarding, direct line to the team.', 'intera' ),
						'contacts_page__apply_as_early_adopter' => __( 'Apply as Early Adopter', 'intera' ),
						'contacts_page__partner_or_reseller' => __( 'Partner or reseller', 'intera' ),
						'contacts_page__you_already_solve_operational_problems_for' => __( 'You already solve operational problems for customers in one industry and want to package that as roles, checks and integrations.', 'intera' ),
						'contacts_page__talk_about_partnership' => __( 'Talk about partnership', 'intera' ),
						'contacts_page__deployment_and_pricing' => __( 'Deployment and pricing', 'intera' ),
						'contacts_page__you_know_what_you_need_and' => __( 'You know what you need and want the commercial detail: installation, integrations, implementation scope and cost.', 'intera' ),
						'contacts_page__see_pricing_first' => __( 'See pricing first', 'intera' ),
						'contacts_page__what_to_send_us' => __( 'What to send us', 'intera' ),
					),
				),
				'contact_routes' => array(
					'label'  => __( 'Contact routes', 'intera' ),
					'fields' => array(
						'contacts_contact_routes__direct' => __( 'Direct', 'intera' ),
						'contacts_contact_routes__talk_to_us' => __( 'Talk to us', 'intera' ),
						'contacts_contact_routes__response_time' => __( 'Response time', 'intera' ),
						'contacts_contact_routes__working_language' => __( 'Working language', 'intera' ),
						'contacts_contact_routes__bring_us_a_real_problem' => __( 'Bring us a real problem', 'intera' ),
						'contacts_contact_routes__connect_on_linkedin' => __( 'Connect on LinkedIn', 'intera' ),
					),
				),
				'who_to_talk_to' => array(
					'label'  => __( 'Who to talk to', 'intera' ),
					'fields' => array(
						'contacts_who_to_talk_to__three_reasons_people_write_to_us' => __( 'Three reasons people write to us', 'intera' ),
						'contacts_who_to_talk_to__documentation' => __( 'Documentation', 'intera' ),
						'contacts_who_to_talk_to__documentation_2' => __( 'Documentation', 'intera' ),
						'contacts_who_to_talk_to__faq' => __( 'FAQ', 'intera' ),
						'contacts_who_to_talk_to__faq_2' => __( 'FAQ', 'intera' ),
						'contacts_who_to_talk_to__prefer_to_read_first_1_s' => __( 'Prefer to read first? %1$s and %2$s answer most first questions.', 'intera' ),
					),
				),
			),
		),
		'request' => array(
			'label'    => __( 'Contact request page', 'intera' ),
			'template' => 'page-contact-request.php',
			'sections' => array(
				'header' => array(
					'label'  => __( 'Header', 'intera' ),
					'fields' => array(
						'request_headline' => __( 'Bring us a real problem', 'intera' ),
					),
				),
				'request_form' => array(
					'label'  => __( 'Request form', 'intera' ),
					'fields' => array(
						'request_request_form__anna_kovalenko' => __( 'Anna Kovalenko', 'intera' ),
						'request_request_form__name' => __( 'Name', 'intera' ),
						'request_request_form__a_kovalenko_company_com' => __( 'a.kovalenko@company.com', 'intera' ),
						'request_request_form__work_email' => __( 'Work email', 'intera' ),
						'request_request_form__company_name' => __( 'Company name', 'intera' ),
						'request_request_form__company' => __( 'Company', 'intera' ),
						'request_request_form__billing_operations_manager' => __( 'Billing Operations Manager', 'intera' ),
						'request_request_form__your_role' => __( 'Your role', 'intera' ),
						'request_request_form__the_area_you_are_responsible_for' => __( 'The area you are responsible for.', 'intera' ),
						'request_request_form__choose_an_industry' => __( 'Choose an industry', 'intera' ),
						'request_request_form__industry' => __( 'Industry', 'intera' ),
						'request_request_form__choose_one' => __( 'Choose one', 'intera' ),
						'request_request_form__what_brings_you_here' => __( 'What brings you here', 'intera' ),
						'request_request_form__every_month_someone_exports_usage_from' => __( 'Every month someone exports usage from mediation and compares it with billing by hand. Last quarter we found unbilled usage six weeks late.', 'intera' ),
						'request_request_form__the_problem_in_your_words' => __( 'The problem, in your words', 'intera' ),
						'request_request_form__what_is_checked_manually_today_which' => __( 'What is checked manually today, which systems are involved, and what happens when it is noticed too late.', 'intera' ),
						'request_request_form__send_request' => __( 'Send request', 'intera' ),
						'request_request_form__we_use_what_you_send_only' => __( 'We use what you send only to answer you. See the %s.', 'intera' ),
						'request_request_form__privacy_policy' => __( 'privacy policy', 'intera' ),
						'request_request_form__we_use_what_you_send_only_2' => __( 'We use what you send only to answer you.', 'intera' ),
						'request_request_form__reference_s' => __( 'Reference: %s', 'intera' ),
						'request_request_form__answer_expected_s' => __( 'Answer expected: %s', 'intera' ),
						'request_request_form__read_the_docs' => __( 'Read the docs', 'intera' ),
						'request_request_form__send_another_request' => __( 'Send another request', 'intera' ),
						'request_request_form__what_happens_next' => __( 'What happens next', 'intera' ),
						'request_request_form__we_read_it_and_answer' => __( 'We read it and answer', 'intera' ),
						'request_request_form__usually_the_same_working_day_no' => __( 'Usually the same working day. No sales sequence.', 'intera' ),
						'request_request_form__one_call_30_minutes' => __( 'One call, 30 minutes', 'intera' ),
						'request_request_form__we_map_the_problem_to_a' => __( 'We map the problem to a role, metrics and the systems involved.', 'intera' ),
						'request_request_form__one_role_one_result' => __( 'One role, one result', 'intera' ),
						'request_request_form__we_set_up_the_first_check' => __( 'We set up the first check on real data and see whether it finds anything.', 'intera' ),
						'request_request_form__early_adopter_programme' => __( 'Early Adopter programme', 'intera' ),
						'request_request_form__free_for_the_first_12_months' => __( 'Free for the first 12 months, unlimited roles, custom onboarding and one role package included. We take a small number of companies during the private beta.', 'intera' ),
						'request_request_form__see_what_is_included' => __( 'See what is included', 'intera' ),
						'request_request_form__prefer_a_direct_line_message_s' => __( 'Prefer a direct line? Message %s.', 'intera' ),
					),
				),
				'say_yes' => array(
					'label'  => __( 'What happens if you say yes', 'intera' ),
					'fields' => array(
						'request_say_yes__what_happens_if_i_say' => __( 'What happens if I say yes?', 'intera' ),
						'request_say_yes__apply_for_the_early_adopter_program' => __( 'Apply for the Early Adopter Program', 'intera' ),
						'request_say_yes__tell_us_briefly_about_your_company' => __( 'Tell us briefly about your company and one operational problem you would like to solve.', 'intera' ),
						'request_say_yes__we_are_currently_inviting_only_a' => __( 'We are currently inviting only a small number of Early Adopters, and we select projects where we believe INTERA can produce a useful result quickly.', 'intera' ),
						'request_say_yes__we_agree_on_one_problem' => __( 'We agree on one problem', 'intera' ),
						'request_say_yes__no_company_wide_implementation' => __( 'No company-wide implementation.', 'intera' ),
						'request_say_yes__we_choose_one_role_one_operational' => __( 'We choose one role, one operational problem and one clear outcome.', 'intera' ),
						'request_say_yes__we_connect_the_required_data' => __( 'We connect the required data', 'intera' ),
						'request_say_yes__intera_works_with_your_existing_systems' => __( 'INTERA works with your existing systems.', 'intera' ),
						'request_say_yes__no_migration_and_no_replacement_of' => __( 'No migration and no replacement of your ERP, CRM or operational tools.', 'intera' ),
						'request_say_yes__we_build_the_first_working_view' => __( 'We build the first working view with you', 'intera' ),
						'request_say_yes__this_may_be_a_health_view' => __( 'This may be a health view, reconciliation, metric, alert or another focused operational use case.', 'intera' ),
						'request_say_yes__the_goal_is_simple_produce_something' => __( 'The goal is simple: produce something useful from real company data.', 'intera' ),
						'request_say_yes__you_use_it_in_real_work' => __( 'You use it in real work', 'intera' ),
						'request_say_yes__your_team_uses_the_result_and' => __( 'Your team uses the result and tells us what works, what does not and what needs to change.', 'intera' ),
						'request_say_yes__as_an_invited_early_adopter_you' => __( 'As an invited Early Adopter, you get direct access to the INTERA team and influence the product while it is still being shaped.', 'intera' ),
						'request_say_yes__then_we_decide_whether_to_expand' => __( 'Then we decide whether to expand', 'intera' ),
						'request_say_yes__if_intera_proves_useful_we_can' => __( 'If INTERA proves useful, we can add more roles, systems and operational problems.', 'intera' ),
						'request_say_yes__if_it_does_not_there_is' => __( 'If it does not, there is no obligation to continue.', 'intera' ),
						'request_say_yes__start_with_one_problem_prove_the' => __( 'Start with one problem. Prove the result. Expand only if it makes sense.', 'intera' ),
					),
				),
			),
		),
		'about' => array(
			'label'    => __( 'About us page', 'intera' ),
			'template' => 'page-about.php',
			'sections' => array(
				'header' => array(
					'label'  => __( 'Header', 'intera' ),
					'fields' => array(
						'about_headline' => __( 'Built by people who have lived this problem', 'intera' ),
					),
				),
				'people' => array(
					'label'  => __( 'The people', 'intera' ),
					'fields' => array(
						'about_people__the_people' => __( 'The people', 'intera' ),
						'about_people__sergey_bogdanov' => __( 'Sergey Bogdanov', 'intera' ),
						'about_people__founder' => __( 'Founder', 'intera' ),
						'about_people__linkedin' => __( 'LinkedIn', 'intera' ),
						/*
						 * Empty on purpose: the same profile is already the
						 * site's direct contact (Customizer → Contacts →
						 * "Direct contact link"), and two fields holding one
						 * URL is one of them going stale. Left blank, this
						 * person's card follows that one setting; a second
						 * person, whose link is their own, fills it in here.
						 */
						'about_people__linkedin_url' => array(
							'default' => '',
							'label'   => __( 'Founder — profile link (URL). Empty follows the Customizer’s “Direct contact link”.', 'intera' ),
						),
						'about_people__talk_to_us' => __( 'Talk to us', 'intera' ),
					),
				),
			),
		),
		'role_sysadmin' => array(
			'label'    => __( 'Role landing: Sysadmin', 'intera' ),
			'template' => 'page-role-sysadmin.php',
			'sections' => array(
				'role_sysadmin_hero' => array(
					'label'  => __( 'Hero', 'intera' ),
					'fields' => array(
						'role_sysadmin_hero__sysadmin_role' => __( 'Sysadmin Role', 'intera' ),
						'role_sysadmin_hero__see_what_needs_attention_before_someone' => __( 'See what needs attention before someone blames IT.', 'intera' ),
						'role_sysadmin_hero__intera_brings_together_selected_signals_from' => __( 'INTERA brings together selected signals from your existing monitoring, backup, service, ticketing and infrastructure systems, so you can quickly see what is weak, stale, failing or becoming risky.', 'intera' ),
						'role_sysadmin_hero__try_the_free_sysadmin_package' => __( 'Try the free Sysadmin Package', 'intera' ),
						'role_sysadmin_hero__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
						'role_sysadmin_hero__know_what_is_failing' => __( 'Know what is failing', 'intera' ),
						'role_sysadmin_hero__know_where_to_investigate' => __( 'Know where to investigate', 'intera' ),
						'role_sysadmin_hero__have_evidence_when_someone_asks' => __( 'Have evidence when someone asks', 'intera' ),
						'role_sysadmin_hero__stop_carrying_the_blame_for_problems' => __( 'Stop carrying the blame for problems outside your control', 'intera' ),
					),
				),
				'role_sysadmin_shows' => array(
					'label'  => __( 'What INTERA shows', 'intera' ),
					'fields' => array(
						'role_sysadmin_shows__what_intera_shows_you' => __( 'What INTERA shows you', 'intera' ),
						'role_sysadmin_shows__above_the_tools_you_already_run' => __( 'Above the tools you already run', 'intera' ),
						'role_sysadmin_shows__intera_sits_above_the_tools_you' => __( 'INTERA sits above the tools you already use and highlights the few things that deserve attention.', 'intera' ),
						'role_sysadmin_shows__what_intera_is_not' => __( 'What INTERA is not', 'intera' ),
						'role_sysadmin_shows__not_a_replacement_for_zabbix' => __( 'Not a replacement for Zabbix', 'intera' ),
						'role_sysadmin_shows__not_a_replacement_for_grafana' => __( 'Not a replacement for Grafana', 'intera' ),
						'role_sysadmin_shows__not_another_nms' => __( 'Not another NMS', 'intera' ),
						'role_sysadmin_shows__not_a_ticketing_system' => __( 'Not a ticketing system', 'intera' ),
						'role_sysadmin_shows__it_operations_health' => __( 'IT Operations Health', 'intera' ),
						'role_sysadmin_shows__health_score' => array(
							'default' => __( '87%', 'intera' ),
							'label'   => __( 'Health view: the overall score', 'intera' ),
						),
						'role_sysadmin_shows__systems_healthy' => __( 'Systems healthy', 'intera' ),
						'role_sysadmin_shows__healthy_count' => array(
							'default' => __( '24', 'intera' ),
							'label'   => __( 'Health view: how many are healthy', 'intera' ),
						),
						'role_sysadmin_shows__need_attention' => __( 'Need attention', 'intera' ),
						'role_sysadmin_shows__attention_count' => array(
							'default' => __( '3', 'intera' ),
							'label'   => __( 'Health view: how many need attention', 'intera' ),
						),
						'role_sysadmin_shows__critical' => __( 'Critical', 'intera' ),
						'role_sysadmin_shows__critical_count' => array(
							'default' => __( '1', 'intera' ),
							'label'   => __( 'Health view: how many are critical', 'intera' ),
						),
						'role_sysadmin_shows__what_needs_attention_first' => __( 'What needs attention first', 'intera' ),
						'role_sysadmin_shows__backup_failed_overnight' => __( 'Backup failed overnight', 'intera' ),
						'role_sysadmin_shows__ssl_certificate_expires_in_9_days' => __( 'SSL certificate expires in 9 days', 'intera' ),
						'role_sysadmin_shows__server_disk_usage_at_91' => __( 'Server disk usage at 91%', 'intera' ),
						'role_sysadmin_shows__accounting_api_unavailable' => __( 'Accounting API unavailable', 'intera' ),
						'role_sysadmin_shows__monitoring_data_stale_for_3_hours' => __( 'Monitoring data stale for 3 hours', 'intera' ),
						'role_sysadmin_shows__example_signals' => __( 'Example signals', 'intera' ),
						'role_sysadmin_shows__server_alive_dead' => __( 'server alive/dead', 'intera' ),
						'role_sysadmin_shows__disk_space' => __( 'disk space', 'intera' ),
						'role_sysadmin_shows__backup_success_failure' => __( 'backup success/failure', 'intera' ),
						'role_sysadmin_shows__certificate_expiry' => __( 'certificate expiry', 'intera' ),
						'role_sysadmin_shows__api_service_availability' => __( 'API/service availability', 'intera' ),
						'role_sysadmin_shows__database_backup_status' => __( 'database backup status', 'intera' ),
						'role_sysadmin_shows__external_service_dependency' => __( 'external service dependency', 'intera' ),
						'role_sysadmin_shows__unresolved_infrastructure_tickets' => __( 'unresolved infrastructure tickets', 'intera' ),
						'role_sysadmin_shows__licence_subscription_expiry' => __( 'licence/subscription expiry', 'intera' ),
						'role_sysadmin_shows__integration_data_feed_failure' => __( 'integration/data feed failure', 'intera' ),
						'role_sysadmin_shows__evidence_behind_every_result' => __( 'Evidence behind every result', 'intera' ),
						'role_sysadmin_shows__source_system' => __( 'source system', 'intera' ),
						'role_sysadmin_shows__current_value' => __( 'current value', 'intera' ),
						'role_sysadmin_shows__previous_value' => __( 'previous value', 'intera' ),
						'role_sysadmin_shows__last_successful_update' => __( 'last successful update', 'intera' ),
						'role_sysadmin_shows__related_systems_and_assets' => __( 'related systems and assets', 'intera' ),
						'role_sysadmin_shows__why_intera_marked_it_unhealthy' => __( 'why INTERA marked it unhealthy', 'intera' ),
						'role_sysadmin_shows__intera_helps_you_prove_what_happened' => __( 'INTERA helps you prove what happened, not just raise another alert.', 'intera' ),
						'role_sysadmin_shows__where_monitoring_stops' => __( 'Where monitoring stops', 'intera' ),
						'role_sysadmin_shows__monitoring_says_the_service_is_up' => __( 'Monitoring says the service is up, but the customer ticket says it is unusable.', 'intera' ),
						'role_sysadmin_shows__the_backup_job_says_completed_but' => __( 'The backup job says completed, but the expected backup file is missing.', 'intera' ),
						'role_sysadmin_shows__the_server_is_online_but_the' => __( 'The server is online, but the application API is unavailable.', 'intera' ),
						'role_sysadmin_shows__an_asset_exists_in_the_cmdb' => __( 'An asset exists in the CMDB but not in monitoring.', 'intera' ),
						'role_sysadmin_shows__a_licence_is_active_but_the' => __( 'A licence is active but the service is no longer in use.', 'intera' ),
						'role_sysadmin_shows__why_not_just_use_zabbix' => __( 'Why not just use Zabbix?', 'intera' ),
						'role_sysadmin_shows__zabbix_tells_you_what_is_happening' => __( 'Zabbix tells you what is happening inside monitored infrastructure. INTERA helps combine that information with other operational systems and show whether the wider business state makes sense.', 'intera' ),
						'role_sysadmin_shows__existing_tools' => __( 'Existing tools', 'intera' ),
						'role_sysadmin_shows__zabbix_backup_system_ticketing_sql_api' => __( 'Zabbix · backup system · ticketing · SQL/API', 'intera' ),
						'role_sysadmin_shows__intera' => __( 'INTERA', 'intera' ),
						'role_sysadmin_shows__one_role_one_set_of_checks' => __( 'one role · one set of checks', 'intera' ),
						'role_sysadmin_shows__attention_health_evidence' => __( 'Attention · Health · Evidence', 'intera' ),
						'role_sysadmin_shows__3_things_need_attention' => __( '3 things need attention', 'intera' ),
					),
				),
				'role_sysadmin_package' => array(
					'label'  => __( 'Free Sysadmin Package', 'intera' ),
					'fields' => array(
						'role_sysadmin_package__included_free_with_every_plan' => __( 'Included free with every plan', 'intera' ),
						'role_sysadmin_package__free_sysadmin_package' => __( 'Free Sysadmin Package', 'intera' ),
						'role_sysadmin_package__the_package_is_a_starter_set' => __( 'The package is a starter set of asset types, metrics, health rules, reconciliations and dashboard views — enough to see something useful on the first day.', 'intera' ),
						'role_sysadmin_package__what_the_package_contains' => __( 'What the package contains', 'intera' ),
						'role_sysadmin_package__server_asset_type' => __( 'Server asset type', 'intera' ),
						'role_sysadmin_package__service_application_asset_type' => __( 'Service and application asset type', 'intera' ),
						'role_sysadmin_package__backup_health_metrics' => __( 'Backup health metrics', 'intera' ),
						'role_sysadmin_package__availability_metrics' => __( 'Availability metrics', 'intera' ),
						'role_sysadmin_package__storage_metrics' => __( 'Storage metrics', 'intera' ),
						'role_sysadmin_package__certificate_expiry' => __( 'Certificate expiry', 'intera' ),
						'role_sysadmin_package__dependency_health' => __( 'Dependency health', 'intera' ),
						'role_sysadmin_package__it_attention_dashboard' => __( 'IT attention dashboard', 'intera' ),
						'role_sysadmin_package__basic_reconciliations' => __( 'Basic reconciliations', 'intera' ),
						'role_sysadmin_package__where_the_signals_come_from' => __( 'Where the signals come from', 'intera' ),
						'role_sysadmin_package__monitoring_systems' => __( 'Monitoring systems', 'intera' ),
						'role_sysadmin_package__sql_databases' => __( 'SQL databases', 'intera' ),
						'role_sysadmin_package__backup_systems' => __( 'Backup systems', 'intera' ),
						'role_sysadmin_package__helpdesk_and_ticketing' => __( 'Helpdesk and ticketing', 'intera' ),
						'role_sysadmin_package__cloud_and_service_apis' => __( 'Cloud and service APIs', 'intera' ),
						'role_sysadmin_package__accounting_or_erp_apis_where_relevant' => __( 'Accounting or ERP APIs, where relevant', 'intera' ),
						'role_sysadmin_package__generic_http_api_checks_through_your' => __( 'Generic HTTP and API checks through your existing monitoring platform', 'intera' ),
						'role_sysadmin_package__it_is_designed_to_work_with' => __( 'It is designed to work with the systems you already run. Nothing here asks you to deploy INTERA-specific monitoring infrastructure first.', 'intera' ),
					),
				),
				'role_sysadmin_cta' => array(
					'label'  => __( 'Private Beta', 'intera' ),
					'fields' => array(
						'role_sysadmin_cta__private_beta' => __( 'Private Beta', 'intera' ),
						'role_sysadmin_cta__bring_us_one_recurring_it_problem' => __( 'Bring us one recurring IT problem', 'intera' ),
						'role_sysadmin_cta__we_will_start_with_one_role' => __( 'We will start with one role, one problem and one useful result.', 'intera' ),
						'role_sysadmin_cta__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
					),
				),
			),
		),
		'role_finance' => array(
			'label'    => __( 'Role landing: Finance', 'intera' ),
			'template' => 'page-role-finance.php',
			'sections' => array(
				'role_finance_hero' => array(
					'label'  => __( 'Hero', 'intera' ),
					'fields' => array(
						'role_finance_hero__finance_management' => __( 'Finance Management', 'intera' ),
						'role_finance_hero__know_where_the_numbers_do_not' => __( 'Know where the numbers do not agree', 'intera' ),
						'role_finance_hero__finance_teams_often_spend_time_checking' => __( 'Finance teams often spend time checking whether billing, accounting, payments and operational records tell the same story. INTERA continuously compares selected data across your existing systems and highlights the few items that need investigation — without replacing your accounting or ERP software.', 'intera' ),
						'role_finance_hero__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
						'role_finance_hero__see_how_intera_works' => __( 'See how INTERA works', 'intera' ),
						'role_finance_hero__know_where_something_does_not_match' => __( 'Know where something does not match', 'intera' ),
						'role_finance_hero__know_how_significant_it_is' => __( 'Know how significant it is', 'intera' ),
						'role_finance_hero__know_which_records_are_the_evidence' => __( 'Know which records are the evidence', 'intera' ),
					),
				),
				'role_finance_signals' => array(
					'label'  => __( 'What INTERA shows', 'intera' ),
					'fields' => array(
						'role_finance_signals__what_intera_can_help_you_see' => __( 'What INTERA can help you see', 'intera' ),
						'role_finance_signals__invoices_issued_but_not_matched_to' => __( 'Invoices issued but not matched to expected billing', 'intera' ),
						'role_finance_signals__payments_received_but_not_correctly_reflected' => __( 'Payments received but not correctly reflected', 'intera' ),
						'role_finance_signals__supplier_costs_not_yet_rebilled' => __( 'Supplier costs not yet rebilled', 'intera' ),
						'role_finance_signals__sales_commitments_that_do_not_match' => __( 'Sales commitments that do not match invoicing', 'intera' ),
						'role_finance_signals__missing_delayed_or_inconsistent_financial_records' => __( 'Missing, delayed or inconsistent financial records', 'intera' ),
						'role_finance_signals__unusual_changes_that_deserve_a_closer' => __( 'Unusual changes that deserve a closer look', 'intera' ),
						'role_finance_signals__from_checking_everything_to_checking_exceptions' => __( 'From checking everything to checking exceptions', 'intera' ),
						'role_finance_signals__instead_of_repeatedly_reconciling_large_lists' => __( 'Instead of repeatedly reconciling large lists, the finance team sees where something does not match, how significant it is and which records provide the evidence.', 'intera' ),
						'role_finance_signals__less_manual_checking_faster_investigation_better' => __( 'Less manual checking. Faster investigation. Better control over the numbers.', 'intera' ),
					),
				),
				'role_finance_cta' => array(
					'label'  => __( 'Private Beta', 'intera' ),
					'fields' => array(
						'role_finance_cta__private_beta' => __( 'Private Beta', 'intera' ),
						'role_finance_cta__bring_us_one_reconciliation_you_repeat' => __( 'Bring us one reconciliation you repeat every month', 'intera' ),
						'role_finance_cta__we_will_start_with_one_role' => __( 'We will start with one role, one problem and one useful result.', 'intera' ),
						'role_finance_cta__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
					),
				),
			),
		),
		'role_account_management' => array(
			'label'    => __( 'Role landing: Account management', 'intera' ),
			'template' => 'page-role-account-management.php',
			'sections' => array(
				'role_account_hero' => array(
					'label'  => __( 'Hero', 'intera' ),
					'fields' => array(
						'role_account_hero__account_management' => __( 'Account Management', 'intera' ),
						'role_account_hero__know_what_was_promised_and_what' => __( 'Know what was promised — and what is still outstanding', 'intera' ),
						'role_account_hero__account_managers_are_often_responsible_for' => __( 'Account managers are often responsible for the customer relationship, but the evidence behind that relationship sits across CRM, billing, operations, logistics and support. INTERA brings those signals together so you can quickly see whether commitments are being delivered as agreed, what is still pending and where something needs attention.', 'intera' ),
						'role_account_hero__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
						'role_account_hero__see_how_intera_works' => __( 'See how INTERA works', 'intera' ),
						'role_account_hero__know_what_was_delivered_as_agreed' => __( 'Know what was delivered as agreed', 'intera' ),
						'role_account_hero__know_what_is_still_pending' => __( 'Know what is still pending', 'intera' ),
						'role_account_hero__know_the_evidence_behind_both' => __( 'Know the evidence behind both', 'intera' ),
					),
				),
				'role_account_signals' => array(
					'label'  => __( 'What INTERA shows', 'intera' ),
					'fields' => array(
						'role_account_signals__what_intera_can_help_you_see' => __( 'What INTERA can help you see', 'intera' ),
						'role_account_signals__equipment_promised_but_not_yet_delivered' => __( 'Equipment promised but not yet delivered', 'intera' ),
						'role_account_signals__services_agreed_but_not_yet_activated' => __( 'Services agreed but not yet activated', 'intera' ),
						'role_account_signals__discounts_or_prices_that_do_not' => __( 'Discounts or prices that do not match billing', 'intera' ),
						'role_account_signals__deadlines_that_are_slipping' => __( 'Deadlines that are slipping', 'intera' ),
						'role_account_signals__open_support_issues_affecting_delivery' => __( 'Open support issues affecting delivery', 'intera' ),
						'role_account_signals__customer_commitments_that_still_need_follow' => __( 'Customer commitments that still need follow-up', 'intera' ),
						'role_account_signals__go_into_the_customer_conversation_prepared' => __( 'Go into the customer conversation prepared', 'intera' ),
						'role_account_signals__instead_of_checking_several_systems_or' => __( 'Instead of checking several systems or asking colleagues for updates, you see the current state and the evidence behind it.', 'intera' ),
						'role_account_signals__know_what_happened_know_what_did' => __( 'Know what happened. Know what did not. Know what to follow up before the customer asks.', 'intera' ),
					),
				),
				'role_account_cta' => array(
					'label'  => __( 'Private Beta', 'intera' ),
					'fields' => array(
						'role_account_cta__private_beta' => __( 'Private Beta', 'intera' ),
						'role_account_cta__bring_us_one_customer_commitment_you' => __( 'Bring us one customer commitment you chase every week', 'intera' ),
						'role_account_cta__we_will_start_with_one_role' => __( 'We will start with one role, one problem and one useful result.', 'intera' ),
						'role_account_cta__apply_for_private_beta' => __( 'Apply for Private Beta', 'intera' ),
					),
				),
			),
		),
		'roles' => array(
			'label'    => __( 'Roles hub', 'intera' ),
			'template' => 'page-roles.php',
			'sections' => array(
				'roles_landings' => array(
					'label'  => __( 'By role', 'intera' ),
					'fields' => array(
						'roles_landings__start_here' => __( 'Start here', 'intera' ),
						'roles_landings__written_for_the_job_you_actually' => __( 'Written for the job you actually do', 'intera' ),
						'roles_landings__each_page_below_answers_for_one' => __( 'Each page below answers for one job: what INTERA shows you, what it does not try to replace, and where to start.', 'intera' ),
						'roles_landings__see_the_role' => __( 'See the role', 'intera' ),
					),
				),
				'roles_all' => array(
					'label'  => __( 'INTERA Roles', 'intera' ),
					'fields' => array(
						'roles_all__intera_roles' => __( 'INTERA Roles', 'intera' ),
						'roles_all__a_module_built_around_a_responsibility' => __( 'A module built around a responsibility', 'intera' ),
						'roles_all__a_role_arrives_with_its_metrics' => __( 'A Role arrives with its metrics, its checks and its detection logic. These are the ones INTERA ships with — adjust them, or ask for one shaped around your own operation.', 'intera' ),
						'roles_all__see_how_roles_work' => __( 'See how Roles work', 'intera' ),
					),
				),
			),
		),
		'faq' => array(
			'label'    => __( 'FAQ page', 'intera' ),
			'template' => 'page-faq.php',
			'sections' => array(
				'faq_content' => array(
					'label'  => __( 'FAQ content', 'intera' ),
					'fields' => array(
						'faq_faq_content__on_this_page' => __( 'On this page', 'intera' ),
					),
				),
			),
		),
	);
}
